# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-OptreeDiff
version:      0.01
version_from: lib/Devel/OptreeDiff.pm
installdirs:  site
requires:
    Algorithm::Diff:               0
    B:                             0
    B::Asmdata:                    0
    B::Utils:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
