--- #YAML:1.0
name:                Devel-OptreeDiff
version:             2.0
abstract:            Produces diffs of optrees
license:             ~
author:              
    - Joshua b. Jore <josh@grenekatz.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Algorithm::Diff:               0
    B:                             0
    B::Utils:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
